### PR TITLE
http-service/test_service.py: Tear down http server properly

### PR DESCRIPTION
**Pull request by drothlis**
The fact that we weren't calling `TestRunner.kill` in the `runner_ctx`
finally block seems to be a bug introduced in ae296432.

Even once that was fixed, after a `make check` there would be a whole
lot of "service.py" processes left running. It turns out that we were
killing the Flask / Werkzeug reloader process, which was leaving its
children alive. Disabling Flask reloading fixes this problem.

Even once that was fixed, occasionally a test would fail with
"tests_using_hardware docker container already in use". Presumably
the docker subprocess of service.py wasn't being killed or was taking
slightly too long to shut down.

### CODE REVIEW

**Comment by drothlis** [comment]
Even with this fix, `test_that_test_environment_is_specified_by_stbt_version` continues to fail intermittently with:

```
runner = <test_service.TestRunner object at 0x7fe1f3d55050>

    def test_that_test_environment_is_specified_by_stbt_version(runner):
        with expect_tests_to_run(2):
            assert "base-image-message" not in run_setup_state_test(
                runner, "4d8e3f18933b368b9d183fcf27b2de6f173ba0f8")
>           assert run_setup_state_test(
                runner, "b6dd8f520c457e85d10002ec6ee6e93ced04e0d0")[
                "base-image-message"] == "This is version 0.21a"

/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/test_service.py:868: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/test_service.py:789: in run_setup_state_test
    print runner.get("/api/_private/jobs/current/log").text
/usr/lib/python2.7/contextlib.py:24: in __exit__
    self.gen.next()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

count = 1, category = 'default'

    @contextmanager
    def expect_tests_to_run(count, category="default"):
        orig_run_count = run_count(category)
        yield
>       assert count == run_count(category) - orig_run_count
E       assert 1 == (29 - 29)
E        +  where 29 = run_count('default')

/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/test_service.py:410: AssertionError

[...]

----------------- Job Logs ----------------
Cloning into 'jobs/tmpbHUZ15/test-pack'...
done.
fatal: Needed a single revision
fatal: Needed a single revision
Error: No such image or container: 81e71083f9f6
Traceback (most recent call last):
  File "/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/../run-test-job.py", line 387, in <module>
    sys.exit(main(sys.argv))
  File "/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/../run-test-job.py", line 342, in main
    with TestEnvironment(json.loads(args.config)) as docker_args:
  File "/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/../run-test-job.py", line 288, in __enter__
    d = dep.__enter__()
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/drothlis/work/stb-tester.com/stb-tester-one/test-runner/stb-tester-service/http-service/../run-test-job.py", line 165, in build_test_image
    ['docker', 'inspect', '--format={{.Id}}', base_image])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'inspect', '--format={{.Id}}', u'81e71083f9f6']' returned non-zero exit status 1
```

**Comment by wmanley** [comment]
I see it failing with:

    AssertionError: Timeout waiting for job to complete

although this does seem to be due to `docker` being genuinely really-really slow.

**Comment by wmanley** [comment]
I think the slowdown I was experiencing was due to having a linux-image (version 3.19) package installed from debian experimental which didn't have support for aufs, thus it was falling back to device-mapper.  See http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/ for more information.

Currently rebuilding having blown-away my `/var/lib/docker`.

**Comment by wmanley** [comment]
This seems to have solved the slowness issues I was seeing.  `make check-pytest` is reduced from ~240s to ~130s with aufs and a fresh `/var/lib/docker`

**Comment by drothlis** [comment]
Note: We could only get `test_that_test_environment_is_specified_by_stbt_version` to fail when running a full `make check-pytest`, not when running the test on its own or even with half of the other tests.

With 7683986, `make check-pytest` has passed 14 times for me, so I'm pretty confident it's fixed.

**Pull request merged**
