### PR TITLE
test-runner: Allow choice of stbt version with `test_pack.stbt_version`

### PR DESCRIPTION
**Pull request by wmanley**
`test_pack.stbt_version` now determines the version of stbt to use when running tests.  This allows users to make phased migrations of their test pack to newer versions of stbt handling incompaibilities as they go.  This in-turn removes worries that users have when upgrading their appliances.

The different test-pack base images you can use can be specified in the test-job config file.

### CODE REVIEW

**Comment by drothlis** [comment]
`make check-integrationtests` fails:

```
PATH="$PWD/tests/test-install/bin:$PATH" \
common/run-tests.sh -i
test_running_test_pack_by_sha... FAIL
RuntimeError: The test-pack must contain a .stbt.conf file which defines a value for test_pack.stbt_version
test_service_with_videotestsrc... FAIL
RuntimeError: The test-pack must contain a .stbt.conf file which defines a value for test_pack.stbt_version
```

**Comment by drothlis** [comment]
`test_that_we_can_run_tests_in_soak` fails with:

```
    def test_that_we_can_run_tests_in_soak(runner):
        orig_run_count = run_count('default')
        response = start_tests(runner, '25b96a2b04f89e7c8ef3f0a0260992843c212911',
                               ['tests/example_tests.py::test_1',
                                'tests/example_tests.py::test_2'],
                               {'soak': 'run forever'})
>       assert response.status_code == 200
E       assert 500 == 200
E        +  where 500 = <Response [500]>.status_code

[...]

CalledProcessError: Command '[u'git', u'ls-files', u'-z', u'-with-tree=25b96a2b04f89e7c8ef3f0a0260992843c212911', u'config/remote-control/*.lircd.conf']' returned non-zero exit status 128
```

**Comment by drothlis** [comment]
`test_that_i_can_start_a_job_immediately_after_stopping` fails for the same reason.

**Comment by wmanley** [comment]
Right, that was a rebasing error, I'd rebased past 9c8d759 and c0d82a2 but not updated the tests to point to the new SHAs.

**Pull request merged**
